from typing import Protocol

from server.domain.entities import Client, Document, DocumentType, ExtractedData


class ClientRepository(Protocol):
    def save(self, client: Client) -> None: ...
    def get(self, client_id: str) -> Client | None: ...
    def list_all(self) -> list[Client]: ...


class DocumentRepository(Protocol):
    def save(self, document: Document) -> None: ...
    def get(self, document_id: str) -> Document | None: ...
    def list_by_client(self, client_id: str) -> list[Document]: ...


class DocumentTypeRepository(Protocol):
    def save(self, document_type: DocumentType) -> None: ...
    def get(self, document_type_id: str) -> DocumentType | None: ...
    def list_active(self) -> list[DocumentType]: ...


class ExtractedDataRepository(Protocol):
    def save(self, extracted_data: ExtractedData) -> None: ...
    def get_by_document(self, document_id: str) -> ExtractedData | None: ...
