from typing import Protocol

from server.domain.entities import (
    Client,
    Document,
    DocumentStatus,
    DocumentType,
    DriveWatchChannel,
    ExtractedData,
    GoogleSession,
)


class ClientRepository(Protocol):
    def save(self, client: Client) -> None: ...
    def get(self, client_id: str) -> Client | None: ...
    def list_all(self) -> list[Client]: ...


class DocumentRepository(Protocol):
    def save(self, document: Document) -> None: ...
    def get(self, document_id: str) -> Document | None: ...
    def list_by_client(self, client_id: str) -> list[Document]: ...
    def list_all(self, status: DocumentStatus | None = None) -> list[Document]: ...
    def get_by_drive_file_id(self, drive_file_id: str) -> Document | None: ...


class DocumentTypeRepository(Protocol):
    def save(self, document_type: DocumentType) -> None: ...
    def get(self, document_type_id: str) -> DocumentType | None: ...
    def list_active(self) -> list[DocumentType]: ...
    def list_all(self) -> list[DocumentType]: ...


class ExtractedDataRepository(Protocol):
    def save(self, extracted_data: ExtractedData) -> None: ...
    def get_by_document(self, document_id: str) -> ExtractedData | None: ...


class SessionRepository(Protocol):
    def save(self, session: GoogleSession) -> None: ...
    def get(self, session_id: str) -> GoogleSession | None: ...
    def delete(self, session_id: str) -> None: ...
    def delete_for_user(self, email: str) -> None: ...


class DriveWatchChannelRepository(Protocol):
    def save(self, channel: DriveWatchChannel) -> None: ...
    def get_by_channel_id(self, channel_id: str) -> DriveWatchChannel | None: ...
